services:
  api:
    build: ./api
    ports:
      - "8888:8888"
      - "8000:8000"
    command: >
      bash -c "uvicorn SentimentAnalysis:app --host='0.0.0.0' --port=8000 --reload"
    volumes:
      - ./:/notebook