services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    command: >
      bash -c "uvicorn main:app --host='0.0.0.0' --port=8000 --reload"
    volumes:
      - ./api:/home
    networks:
      - api-network
  web:
    build:
      context: ./web
    ports:
      - "8080:8080"
      - "5173:5173"
    volumes:
      - ./web:/app
      - exclude:/app/node_modules/
    command: npm run dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - api-network
    develop:
      watch: 
        - action: sync+restart
          path: ./web
          target: /app
          ignore: 
            - node_modules

networks:
  api-network:
    driver: bridge

volumes:
  exclude: