services:
  web:
    build:
      context: ./web
    ports:
      - "8080:8080"
      - "5173:5173"
    volumes:
      - ./web:/app
      - exclude:/app/node_modules/
    command: npm run dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    develop:
      watch: 
        - action: sync+restart
          path: ./web
          target: /app
          ignore: 
            - node_modules

volumes:
  exclude: