services:
  api:
    build: ./api
    ports:
      - "8888:8888"
      - "8000:8000"
    command: >
      bash -c "uvicorn SentimentAnalysis:app --host='0.0.0.0' --port=8000 --reload"
    volumes:
      - ./:/notebook
    networks:
      - api-network
  web:
    build:
      context: ./web
    ports:
      - "8080:8080"
    volumes:
      - ./web:/app
    command: npm run serve
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    networks:
      - api-network

networks:
  api-network:
    driver: bridge